### ISSUE TITLE
Right side panel brightness not adjustable

### ISSUE THREAD

**Issue by davidc1701** [DiscordStyles/FrostedGlass#33]
**Describe the bug**  
Threads that are opened on the side no longer use the same brightness settings and I couldn't find a way to adjust the brightness of this one section. Threads opened in full view do not have this problem.

**To Reproduce**  
View a thread by clicking on the '**X Messages >**' link in a channel.

**Screenshots**  
![image](https://user-images.githubusercontent.com/48530408/154798447-2104c0a6-5abf-4fd1-8d53-d06bdaf9226d.png)

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows 10
Mod: BetterDiscord
Discord language: English

**Comment by Kyosukyuu** [comment]
Pretty late but I ran into the same issue as you did. I ended up adding a backdrop filter to the outer container of the thread element like so:
```
.container-3XgAHv {
  backdrop-filter: brightness(0.32);
}
```
Users will have to play around with the brightness value since it can be different for everyone. You can also assign the same CSS property to `resizeHandle-PBRzPC` if you want to fill in the vertical strip separating the main window and the thread window.
